In [2]:
import pandas as pd

Pandas Series

In [3]:
ages = pd.Series([22,35,28,41])
print(ages)
print(ages.shape)

0    22
1    35
2    28
3    41
dtype: int64
(4,)

In [4]:
ages = pd.Series([22,35,28,41],index=["Dhanushka","Sandun","Pathum","Kasun"])
print(ages)

Dhanushka    22
Sandun       35
Pathum       28
Kasun        41
dtype: int64

In [5]:
print(ages.loc["Pathum"])

28

In [6]:
ages = pd.Series([25,30,48,75,65])
print(ages.loc[2])
print(ages.shape)

48
(5,)

Pandas DataFrame

In [7]:
df = pd.DataFrame({
    "name":["Dhanushka","Sandun",None,"Pathum","Sunil"],
    "age":[25,54,34,62,47],
    "score":[0.64,0.47,0.58,0.94,0.75]

})

print(df)
print(type(df))

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58
3     Pathum   62   0.94
4      Sunil   47   0.75
<class 'pandas.core.frame.DataFrame'>

Label base accessing

In [8]:
print(df.loc[2,"age"])

34

Index base accessing

In [9]:
print(df.iloc[2,1])

34

In [10]:
print(df.shape)
print("-"*30)
print(df.dtypes)

(5, 3)
------------------------------
name      object
age        int64
score    float64
dtype: object

After data file loading

In [11]:
df

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58
3     Pathum   62   0.94
4      Sunil   47   0.75

In [12]:
df.head(3)

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58

In [13]:
df.tail(2)

     name  age  score
3  Pathum   62   0.94
4   Sunil   47   0.75

In [14]:
df.columns

Index(['name', 'age', 'score'], dtype='object')

In [15]:
list(df.columns)

['name', 'age', 'score']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     5 non-null      int64
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

In [19]:
df = pd.DataFrame({
    "age": [22, 35, 28, 41, 58, 69, 32, 45, 45, 67],
    'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kandt', 'Jaffna', 'Colombo', 'Kandy', 'Galle', 'Colombo'],
    "score": [0.81, 0.44, 0.92, 0.67, 0.85, 0.75, 0.81, 0.44, 0.92, 0.67]
})

In [20]:
df.describe()

             age      score
count  10.000000  10.000000
mean   44.200000   0.728000
std    16.074825   0.174852
min    22.000000   0.440000
25%    32.750000   0.670000
50%    43.000000   0.780000
75%    54.750000   0.840000
max    69.000000   0.920000