In [136]:
import pandas as pd

Pandas Series

In [137]:
ages = pd.Series([22,35,28,41])
print(ages)
print(ages.shape)

0    22
1    35
2    28
3    41
dtype: int64
(4,)

In [138]:
ages = pd.Series([22,35,28,41],index=["Dhanushka","Sandun","Pathum","Kasun"])
print(ages)

Dhanushka    22
Sandun       35
Pathum       28
Kasun        41
dtype: int64

In [139]:
print(ages.loc["Pathum"])

28

In [140]:
ages = pd.Series([25,30,48,75,65])
print(ages.loc[2])
print(ages.shape)

48
(5,)

Pandas DataFrame

In [141]:
df = pd.DataFrame({
    "name":["Dhanushka","Sandun",None,"Pathum","Sunil"],
    "age":[25,54,34,62,47],
    "score":[0.64,0.47,0.58,0.94,0.75]

})

print(df)
print(type(df))

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58
3     Pathum   62   0.94
4      Sunil   47   0.75
<class 'pandas.core.frame.DataFrame'>

Label base accessing

In [142]:
print(df.loc[2,"age"])

34

Index base accessing

In [143]:
print(df.iloc[2,1])

34

In [144]:
print(df.shape)
print("-"*30)
print(df.dtypes)

(5, 3)
------------------------------
name      object
age        int64
score    float64
dtype: object

After data file loading

In [145]:
df

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58
3     Pathum   62   0.94
4      Sunil   47   0.75

In [146]:
df.head(3)

        name  age  score
0  Dhanushka   25   0.64
1     Sandun   54   0.47
2       None   34   0.58

In [147]:
df.tail(2)

     name  age  score
3  Pathum   62   0.94
4   Sunil   47   0.75

In [148]:
df.columns

Index(['name', 'age', 'score'], dtype='object')

In [149]:
list(df.columns)

['name', 'age', 'score']

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     5 non-null      int64
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

In [151]:
df = pd.DataFrame({
    "age": [22, 35, 28, 41, 58, 69, 32, 45, 45, 67],
    'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kandt', 'Jaffna', 'Colombo', 'Kandy', 'Galle', 'Colombo'],
    "score": [0.81, 0.44, 0.92, 0.67, 0.85, 0.75, 0.81, 0.44, 0.92, 0.67]
})

In [152]:
df.describe()

             age      score
count  10.000000  10.000000
mean   44.200000   0.728000
std    16.074825   0.174852
min    22.000000   0.440000
25%    32.750000   0.670000
50%    43.000000   0.780000
75%    54.750000   0.840000
max    69.000000   0.920000

# Clean and Test Large Dataset

In [153]:
df = pd.read_csv("customer_data-selected-columns.csv")

In [154]:
df.head()

,Customer ID,Age,Gender,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            5050 non-null   int64
 1   Age                    5050 non-null   int64
 2   Gender                 5050 non-null   object
 3   Purchase Amount (USD)  4492 non-null   float64
 4   Location               5050 non-null   object
 5   Size                   4676 non-null   object
 6   Color                  5050 non-null   object
 7   Season                 5050 non-null   object
 8   Review Rating          4448 non-null   float64
 9   Subscription Status    5050 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 394.7+ KB

In [156]:
df.head()

,Customer ID,Age,Gender,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No

In [157]:
print(df.iloc[1:4,3:6])
print(type(df.iloc[1:4,3:6]))

   Purchase Amount (USD)        Location Size
1                   84.0  South Carolina    M
2                   50.0         Montana    M
3                   75.0        Illinois    L
<class 'pandas.core.frame.DataFrame'>

In [158]:

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
print(df.columns)

Index(['customer_id', 'age', 'gender', 'purchase_amount_(usd)', 'location',
       'size', 'color', 'season', 'review_rating', 'subscription_status'],
      dtype='object')

In [159]:
print(df.loc[1:3,"purchase_amount_(usd)":"size"])
print(type(df.loc[1:3,"purchase_amount_(usd)":"size"]))

   purchase_amount_(usd)        location size
1                   84.0  South Carolina    M
2                   50.0         Montana    M
3                   75.0        Illinois    L
<class 'pandas.core.frame.DataFrame'>

In [160]:
print(df["age"])
print(type(df["age"]))

0       22
1       51
2       18
3       22
4       40
        ..
5045    24
5046    19
5047    70
5048    43
5049    62
Name: age, Length: 5050, dtype: int64
<class 'pandas.core.series.Series'>

In [161]:
filterd_data = df[df["age"]<30]
filterd_data
# print(type(filterd_data))

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
5,3583,23,Female,41.0,California,S,Beige,Summer,3.4,No
19,2134,21,Male,34.0,Maine,M,Olive,Summer,3.8,No
...,...,...,...,...,...,...,...,...,...,...
5040,926,22,Male,88.0,Arizona,L,Teal,Winter,4.9,Yes
5041,826,27,Male,94.0,Nebraska,XL,Brown,Fall,3.6,Yes
5042,1721,25,Male,84.0,Massachusetts,S,Beige,Winter,2.8,No
5045,913,24,Male,56.0,Arkansas,M,Green,Winter,3.4,Yes
5046,3466,19,Female,53.0,Iowa,M,Gold,Spring,3.4,No

In [162]:
filtered_data = df[(df["color"]=="Beige") & (df["review_rating"]<3.0)]
filtered_data

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
268,3208,67,Female,29.0,Arizona,XL,Beige,Summer,2.7,No
325,3243,45,Female,74.0,Oregon,S,Beige,Fall,2.8,No
566,319,45,Male,67.0,South Dakota,M,Beige,Winter,2.5,Yes
679,3179,66,Female,34.0,Washington,L,Beige,Spring,2.7,No
804,1060,22,Male,34.0,North Carolina,M,Beige,Winter,2.5,No
865,3436,68,Female,91.0,Montana,M,Beige,Summer,2.7,No
1015,1072,61,Male,81.0,Pennsylvania,M,Beige,Summer,2.6,No
1049,144,30,Male,48.0,Missouri,M,Beige,Fall,2.7,Yes
1130,1020,32,Male,76.0,Kentucky,S,Beige,Winter,2.8,Yes
1215,3066,49,Female,59.0,North Dakota,M,Beige,Fall,2.8,No
1472,519,24,Male,100.0,Oregon,M,Beige,Fall,2.9,Yes
1669,225,63,Male,83.0,South Dakota,S,Beige,Summer,2.9,Yes
2111,903,43,Male,44.0,Kentucky,M,Beige,Summer,2.8,Yes
2782,451,25,Male,21.0,Connecticut,L,Beige,Summer,2.7,Yes
2854,3488,25,Female,24.0,West Virginia,L,Beige,Fall,2.9,No
3355,2296,50,Male,22.0,Connecticut,L,Beige,Spring,2.9,No
3740,1097,57,Male,46.0,New Hampshire,S,Beige,Fall,2.6,No
3778,3145,23,Female,70.0,Maine,L,Beige,Spring,2.6,No
3780,349,56,Male,59.0,South Carolina,M,Beige,Fall,2.7,Yes
3787,1693,56,Male,75.0,Utah,M,Beige,Winter,2.6,No
4263,1662,64,Male,86.0,Iowa,S,Beige,Summer,2.7,No
4461,842,55,Male,88.0,Texas,M,Beige,Summer,2.6,Yes
4495,2855,36,Female,28.0,Delaware,M,Beige,Fall,2.7,No
4901,1060,22,Male,34.0,North Carolina,M,Beige,Winter,2.5,No
4925,3419,53,Female,30.0,South Carolina,M,Beige,Summer,2.8,No
4973,965,42,Male,51.0,Arizona,M,Beige,Spring,2.6,Yes
5042,1721,25,Male,84.0,Massachusetts,S,Beige,Winter,2.8,No

In [163]:
df.isna()

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
5045,False,False,False,False,False,False,False,False,False,False
5046,False,False,False,False,False,False,False,False,False,False
5047,False,False,False,False,False,False,False,False,False,False
5048,False,False,False,False,False,False,False,False,False,False
5049,False,False,False,False,False,False,False,False,True,False

In [164]:
df.isna().sum()

customer_id                0
age                        0
gender                     0
purchase_amount_(usd)    558
location                   0
size                     374
color                      0
season                     0
review_rating            602
subscription_status        0
dtype: int64

In [165]:
clear_data=df.dropna()
clear_data

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No
...,...,...,...,...,...,...,...,...,...,...
5044,2229,54,Male,50.0,Kansas,M,Green,Fall,3.7,No
5045,913,24,Male,56.0,Arkansas,M,Green,Winter,3.4,Yes
5046,3466,19,Female,53.0,Iowa,M,Gold,Spring,3.4,No
5047,3572,70,Female,27.0,North Dakota,M,White,Summer,3.2,No
5048,3195,43,Female,52.0,Maryland,L,Gold,Summer,4.6,No

In [166]:
df.isna().sum()

customer_id                0
age                        0
gender                     0
purchase_amount_(usd)    558
location                   0
size                     374
color                      0
season                     0
review_rating            602
subscription_status        0
dtype: int64

In [167]:
df.head(10)

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No
5,3583,23,Female,41.0,California,S,Beige,Summer,3.4,No
6,1135,62,Male,81.0,Wisconsin,M,Brown,Summer,NaN,No
7,1411,61,Male,93.0,Tennessee,M,Purple,Summer,4.0,No
8,113,37,Male,65.0,Florida,M,Red,Spring,4.3,Yes
9,166,42,Male,60.0,Kentucky,S,Yellow,Winter,2.8,Yes

In [168]:
clear_data.head(10)

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No
5,3583,23,Female,41.0,California,S,Beige,Summer,3.4,No
7,1411,61,Male,93.0,Tennessee,M,Purple,Summer,4.0,No
8,113,37,Male,65.0,Florida,M,Red,Spring,4.3,Yes
9,166,42,Male,60.0,Kentucky,S,Yellow,Winter,2.8,Yes
11,947,46,Male,24.0,Pennsylvania,XL,Blue,Spring,2.8,Yes

In [169]:
clear_data.isna().sum()

customer_id              0
age                      0
gender                   0
purchase_amount_(usd)    0
location                 0
size                     0
color                    0
season                   0
review_rating            0
subscription_status      0
dtype: int64

In [170]:
df.isna().sum()

customer_id                0
age                        0
gender                     0
purchase_amount_(usd)    558
location                   0
size                     374
color                      0
season                     0
review_rating            602
subscription_status        0
dtype: int64

In [171]:
df["purchase_amount_(usd)"]=df["purchase_amount_(usd)"].fillna(df["purchase_amount_(usd)"].median())

In [172]:
df["size"]=df["size"].fillna(df["size"].mode()[0])

In [173]:
df["review_rating"]=df["review_rating"].fillna(df["review_rating"].mean())

In [174]:
df.isna().sum()

customer_id              0
age                      0
gender                   0
purchase_amount_(usd)    0
location                 0
size                     0
color                    0
season                   0
review_rating            0
subscription_status      0
dtype: int64

In [175]:
df.duplicated().sum()

np.int64(50)

In [176]:
duplicate=df[df.duplicated(keep=False)]
duplicate

,customer_id,age,gender,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status
176,2834,43,Female,56.0,Arkansas,M,Teal,Fall,3.3,No
271,1698,36,Male,87.0,South Carolina,L,Lavender,Fall,3.5,No
483,974,60,Male,75.0,Colorado,M,Teal,Fall,3.5,Yes
667,3507,18,Female,57.0,Illinois,L,Olive,Winter,3.7,No
707,2069,70,Male,81.0,Vermont,XL,Black,Summer,3.9,No
...,...,...,...,...,...,...,...,...,...,...
4735,2182,22,Male,63.0,Hawaii,M,Black,Fall,3.2,No
4841,2622,48,Male,46.0,Maine,M,Beige,Winter,3.0,No
4887,3875,70,Female,54.0,Nevada,XL,Beige,Summer,3.9,No
4901,1060,22,Male,34.0,North Carolina,M,Beige,Winter,2.5,No
5037,3439,26,Female,71.0,Kentucky,M,Violet,Fall,3.0,No

Find Frequency

In [177]:
df["color"].value_counts()

color
Black        404
Blue         387
Red          367
Green        366
White        365
Olive        181
Yellow       176
Silver       174
Teal         174
Violet       170
Cyan         169
Gray         160
Maroon       159
Orange       157
Pink         155
Charcoal     155
Magenta      153
Peach        152
Lavender     151
Purple       151
Beige        150
Turquoise    147
Indigo       147
Brown        142
Gold         138
Name: count, dtype: int64

In [178]:
df["location"].value_counts()

location
New York          337
Los Angeles       236
Houston           210
Phoenix           208
Chicago           196
Montana            97
California         96
Idaho              96
Illinois           94
Alabama            90
Nebraska           90
Minnesota          90
Nevada             88
Vermont            87
Delaware           87
Maryland           86
Louisiana          84
North Dakota       83
West Virginia      83
Missouri           82
Arkansas           81
Mississippi        81
New Mexico         81
Tennessee          80
Maine              80
Kentucky           80
Virginia           80
Georgia            80
North Carolina     80
Indiana            79
Texas              79
Connecticut        79
Wisconsin          78
Ohio               78
South Carolina     77
Oklahoma           76
Colorado           76
Oregon             75
Pennsylvania       74
Washington         73
Michigan           73
Massachusetts      72
Alaska             72
Wyoming            71
New Hampshire      71
Utah               71
South Dakota       70
Iowa               70
Florida            68
New Jersey         67
Hawaii             66
Arizona            65
Kansas             64
Rhode Island       63
Name: count, dtype: int64

Group By

In [179]:
df.groupby("location")["purchase_amount_(usd)"].mean()

location
Alabama            58.988889
Alaska             67.597222
Arizona            66.553846
Arkansas           60.691358
California         58.927083
Chicago           451.713724
Colorado           56.539474
Connecticut        54.037975
Delaware           55.586207
Florida            55.852941
Georgia            58.550000
Hawaii             57.803030
Houston           358.912286
Idaho              60.447917
Illinois           61.074468
Indiana            58.924051
Iowa               61.328571
Kansas             54.015625
Kentucky           56.062500
Los Angeles       405.715975
Louisiana          57.714286
Maine              56.937500
Maryland           55.755814
Massachusetts      60.888889
Michigan           62.095890
Minnesota          56.733333
Mississippi        61.123457
Missouri           58.085366
Montana            60.319588
Nebraska           59.566667
Nevada             63.272727
New Hampshire      59.422535
New Jersey         56.746269
New Mexico         61.901235
New York          355.549496
North Carolina     60.812500
North Dakota       62.891566
Ohio               60.743590
Oklahoma           57.881579
Oregon             57.346667
Pennsylvania       66.567568
Phoenix           366.636298
Rhode Island       61.444444
South Carolina     58.779221
South Dakota       60.514286
Tennessee          62.937500
Texas              61.037975
Utah               62.577465
Vermont            57.482759
Virginia           62.062500
Washington         63.328767
West Virginia      63.734940
Wisconsin          57.307692
Wyoming            60.690141
Name: purchase_amount_(usd), dtype: float64

In [180]:
df.groupby("location").agg(
    avg_purchase_amount=("purchase_amount_(usd)", "mean"),
    h_rows = ("purchase_amount_(usd)","count"),
    avg_age = ("age","mean")
    
)

                avg_purchase_amount  h_rows    avg_age
location
Alabama                   58.988889      90  44.477778
Alaska                    67.597222      72  43.000000
Arizona                   66.553846      65  45.276923
Arkansas                  60.691358      81  43.888889
California                58.927083      96  42.822917
Chicago                  451.713724     196  45.729592
Colorado                  56.539474      76  44.355263
Connecticut               54.037975      79  47.291139
Delaware                  55.586207      87  43.160920
Florida                   55.852941      68  42.323529
Georgia                   58.550000      80  43.475000
Hawaii                    57.803030      66  42.378788
Houston                  358.912286     210  42.338095
Idaho                     60.447917      96  43.937500
Illinois                  61.074468      94  43.031915
Indiana                   58.924051      79  48.050633
Iowa                      61.328571      70  40.128571
Kansas                    54.015625      64  43.031250
Kentucky                  56.062500      80  42.062500
Los Angeles              405.715975     236  43.750000
Louisiana                 57.714286      84  48.154762
Maine                     56.937500      80  41.612500
Maryland                  55.755814      86  46.895349
Massachusetts             60.888889      72  45.208333
Michigan                  62.095890      73  42.095890
Minnesota                 56.733333      90  45.400000
Mississippi               61.123457      81  43.234568
Missouri                  58.085366      82  45.451220
Montana                   60.319588      97  43.649485
Nebraska                  59.566667      90  42.566667
Nevada                    63.272727      88  43.909091
New Hampshire             59.422535      71  44.323944
New Jersey                56.746269      67  45.029851
New Mexico                61.901235      81  44.024691
New York                 355.549496     337  45.305638
North Carolina            60.812500      80  45.500000
North Dakota              62.891566      83  43.771084
Ohio                      60.743590      78  46.564103
Oklahoma                  57.881579      76  44.223684
Oregon                    57.346667      75  43.466667
Pennsylvania              66.567568      74  42.972973
Phoenix                  366.636298     208  45.423077
Rhode Island              61.444444      63  46.476190
South Carolina            58.779221      77  47.350649
South Dakota              60.514286      70  44.014286
Tennessee                 62.937500      80  44.050000
Texas                     61.037975      79  42.392405
Utah                      62.577465      71  43.309859
Vermont                   57.482759      87  42.712644
Virginia                  62.062500      80  41.412500
Washington                63.328767      73  44.397260
West Virginia             63.734940      83  42.397590
Wisconsin                 57.307692      78  45.256410
Wyoming                   60.690141      71  42.507042

In [181]:
se = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(se)
print(type(se))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>

In [182]:
print(se.loc[2])
print(se.iloc[2])

3
3

In [183]:
df = pd.DataFrame({
    "age":[25,42,36,28,51],
    "city":["Colombo","Kandy","Galle","Rathnapura","Jaffna"],
    "score":[0.81,0.52,0.65,0.37,0.96]
})

df

print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [184]:
df.loc[1:3,"city":"score"]

         city  score
1       Kandy   0.52
2       Galle   0.65
3  Rathnapura   0.37

In [185]:
df = pd.read_csv("customers_tiny.csv")

df

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [186]:
df.head()

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0

In [187]:
df.tail()

    age     city  score  purchased
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [188]:
print(list(df.columns))

['age', 'city', 'score', 'purchased']

In [189]:
print(df["age"])

0    22.0
1    35.0
2    28.0
3    41.0
4     NaN
5    33.0
Name: age, dtype: float64

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        5 non-null      float64
 1   city       6 non-null      object
 2   score      5 non-null      float64
 3   purchased  6 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 324.0+ bytes

In [191]:
df.describe()

             age     score  purchased
count   5.000000  5.000000   6.000000
mean   31.800000  0.674000   0.666667
std     7.190271  0.186896   0.516398
min    22.000000  0.440000   0.000000
25%    28.000000  0.550000   0.250000
50%    33.000000  0.670000   1.000000
75%    35.000000  0.810000   1.000000
max    41.000000  0.900000   1.000000

In [192]:
df.head()

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0

In [193]:
print(df.iloc[1:4,1::])

      city  score  purchased
1    Kandy   0.44          0
2    Galle    NaN          1
3  Colombo   0.67          1

In [194]:
print(df[df["age"]>30])

    age     city  score  purchased
1  35.0    Kandy   0.44          0
3  41.0  Colombo   0.67          1
5  33.0    Galle   0.90          1

In [195]:
filtered = df[(df["city"]=="Colombo") & (df["score"]>0.5)]
print(filtered)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
3  41.0  Colombo   0.67          1

In [196]:
df

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [198]:
clean_data=df.dropna()
clean_data

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
3  41.0  Colombo   0.67          1
5  33.0    Galle   0.90          1

In [199]:
print(df.isna())

     age   city  score  purchased
0  False  False  False      False
1  False  False  False      False
2  False  False   True      False
3  False  False  False      False
4   True  False  False      False
5  False  False  False      False

In [200]:
df.isna().sum()

age          1
city         0
score        1
purchased    0
dtype: int64

In [202]:
df["age"] = df["age"].fillna(df["age"].median())
df

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4  33.0    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [203]:
df["score"] = df["score"].fillna(df["score"].mean())
df

    age     city  score  purchased
0  22.0  Colombo  0.810          1
1  35.0    Kandy  0.440          0
2  28.0    Galle  0.674          1
3  41.0  Colombo  0.670          1
4  33.0    Kandy  0.550          0
5  33.0    Galle  0.900          1

In [208]:
df["age"].dtype

dtype('float64')

In [211]:
df["age"] = df["age"].astype("int64")
print(df["age"].dtype)

int64

In [213]:
print(df.sort_values("age"))

   age     city  score  purchased
0   22  Colombo  0.810          1
2   28    Galle  0.674          1
5   33    Galle  0.900          1
4   33    Kandy  0.550          0
1   35    Kandy  0.440          0
3   41  Colombo  0.670          1

In [215]:
print(df.sort_values("score",ascending=False))

   age     city  score  purchased
5   33    Galle  0.900          1
0   22  Colombo  0.810          1
2   28    Galle  0.674          1
3   41  Colombo  0.670          1
4   33    Kandy  0.550          0
1   35    Kandy  0.440          0

In [216]:
df["distance"]=[20,45,87,69,36,10]
df

   age     city  score  purchased  distance
0   22  Colombo  0.810          1        20
1   35    Kandy  0.440          0        45
2   28    Galle  0.674          1        87
3   41  Colombo  0.670          1        69
4   33    Kandy  0.550          0        36
5   33    Galle  0.900          1        10

In [217]:
df.loc[len(df)] = [25,"Rathnapura",0.85,1,48]
df

   age        city  score  purchased  distance
0   22     Colombo  0.810          1        20
1   35       Kandy  0.440          0        45
2   28       Galle  0.674          1        87
3   41     Colombo  0.670          1        69
4   33       Kandy  0.550          0        36
5   33       Galle  0.900          1        10
6   25  Rathnapura  0.850          1        48